### ISSUE TITLE
missing node attributes

### ISSUE THREAD

**Issue by kmanohar1** [chef-cookbooks/ohai#52]
### Cookbook version
Latest
### Chef-client version
12.15.19
### Platform Details
Linux

Here is my code:
File ol_ohai_plugin.rb has the following content
```
Ohai.plugin(:ol_ohai_plugin) do
  provides "oci_ol_km"
  collect_data(:default) do
    oci_ol_km Mash.new
    oci_ol_km[:ipaddress]="127.0.0.1"
  end
end
```
File - recipes/ol_translator.rb
```
`require 'json'

ohai_plugin 'My Ohai Plugin' do
  name 'ol_ohai_plugin'
  path '/var/tmp'
end

puts "**********************************"
puts node[:oci_ol_km][:ipaddress]
puts "**********************************"
```

`
When I run this code from my workstation on a node 'node10', I am not seeing my node attributes populated in the node object under 'automatic'.

From my workstation, I run it as follows:
`knife ssh ip_address_of_node_10 'chef-client'`
Please let me know what am I missing

**Comment by tas50** [comment]
Try changing 

```ruby
collect_data(:default) do
```

to 

```ruby
collect_data do
```

**Comment by tas50** [comment]
I believe what you're running into is a compile time vs. converge time problem in your recipe. Chef runs in two different phases. The first is a compile time phase where Ruby is evaluated. The 2nd phase involves actually converging each of the resources. The ```puts``` statements are actually running before the plugin is installed since the ```puts``` statements happen in the compile phase. You can work around some of this by adding ```compile_time true``` to the ohai plugin, but also testing with puts is going to be problematic since it's running during compile time. For troubleshooting you might have a better time adding chef ```log``` resources to the recipe as those will execute during the converge.

A nice blog explaining the Chef run process:
https://coderanger.net/two-pass/

The log resource:
https://docs.chef.io/resource_log.html
