### ISSUE TITLE
Release 5.0.1 is broken

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/ohai#62]
See comments in 
https://github.com/chef-cookbooks/ohai/commit/d6bfb34a7907295f2960e1f9d6f9afa1d10ce71d

**Comment by bcg62** [comment]
same

**Comment by tas50** [comment]
5.0.2 has been released, but I'm curious what versions of Chef everyone here is on

**Comment by cullenmcdermott** [comment]
12.19.36 is what I'm on.

**Comment by rmoriz** [comment]
chef -v  
Chef Development Kit Version: 1.2.22
chef-client version: 12.19.36
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.4
kitchen version: 1.16.0

**Comment by bcg62** [comment]
Chef 12.19.36

**Comment by wsoula** [comment]
We ran into this problem as well and 5.0.2 fixed it:
```
wsoula@aus2-orca-d1:~$ chef-client -v
Chef: 12.15.19
```

**Comment by tas50** [comment]
We figured out the root cause is actually defining the action class before the actions. This causes the class_eval to fail. I've opened a PR to move the action_class to the end of each resource which fixes the issue. We also have a PR in the works that resolves the bug in Chef itself so that Chef 13 will just do the right thing. Using action_class.class_eval again will give us back compatibility with Chef 12.5 and 12.6, which are both heavily used.
